timeout = 10
default = 0

[entry]
label   = Arch Linux
type    = linux
path    = \vmlinuz-linux
initrd  = \initramfs-linux.img
args    = root=/dev/sda2 rw quiet loglevel=3
default = true

[entry]
label   = Arch Linux (verbose)
type    = linux
path    = \vmlinuz-linux
initrd  = \initramfs-linux.img
args    = root=/dev/sda2 rw loglevel=7 earlyprintk

[entry]
label   = Arch Linux (fallback)
type    = linux
path    = \vmlinuz-linux
initrd  = \initramfs-linux-fallback.img
args    = root=/dev/sda2 rw